---

- name: test if terraform_version is set correctly
  assert:
    that:
      - terraform_version is defined
      - terraform_version is string
    quiet: yes

- name: test if terraform_destination is set correctly
  assert:
    that:
      - terraform_destination is defined
      - terraform_destination is defined
    quiet: yes
