---
# tasks file for terraform
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: download and install software
  unarchive:
    src: "{{ terraform_unarchive_src }}"
    dest: "{{ terraform_destination }}"
    remote_src: yes
    mode: "755"
    owner: root
    group: root
